Vagrant.configure("2") do |config|

    # Criando Servidor DNS
    config.vm.define "dnsserver" do |dnsserver|
      
      dnsserver.vm.box = "hashicorp/bionic64"
      dnsserver.vm.network "private_network", ip: "192.168.33.2"
      
      dnsserver.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y bind9 #servidor para protocolo DNS
        sudo systemctl start bind9
        sudo systemctl enable bind9
        sudo sh -c "echo 'zone \"localdomain\" {' > /etc/bind/named.conf.local"
        sudo sh -c "echo '  type master;' >> /etc/bind/named.conf.local"
        sudo sh -c "echo '  file \"/etc/bind/db.localdomain\";' >> /etc/bind/named.conf.local"
      SHELL
    
    end
  
  end